// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: content.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteCulturalElementRelation = `-- name: DeleteCulturalElementRelation :exec
DELETE FROM cultural_element_relations
WHERE LEAST(element_key, related_element_key) = LEAST(
        $1::text,
        $2::text
    )
  AND GREATEST(element_key, related_element_key) = GREATEST(
        $1::text,
        $2::text
    )
`

type DeleteCulturalElementRelationParams struct {
	ElementKey        string `json:"element_key"`
	RelatedElementKey string `json:"related_element_key"`
}

func (q *Queries) DeleteCulturalElementRelation(ctx context.Context, arg DeleteCulturalElementRelationParams) error {
	_, err := q.db.Exec(ctx, deleteCulturalElementRelation, arg.ElementKey, arg.RelatedElementKey)
	return err
}

const getAttraction = `-- name: GetAttraction :one
SELECT key, name, created_at, updated_at
FROM attractions
WHERE key = $1
`

func (q *Queries) GetAttraction(ctx context.Context, attractionKey string) (Attraction, error) {
	row := q.db.QueryRow(ctx, getAttraction, attractionKey)
	var i Attraction
	err := row.Scan(
		&i.Key,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAttractionCulturalIntroduction = `-- name: GetAttractionCulturalIntroduction :one
SELECT
    introduction.key,
    introduction.name,
    introduction.introduction,
    introduction.cultural_element_key,
    element.name AS cultural_element_name,
    introduction.attraction_key,
    attraction.name AS attraction_name,
    introduction.latitude,
    introduction.longitude,
    introduction.created_at,
    introduction.updated_at
FROM attraction_cultural_introductions AS introduction
JOIN cultural_elements AS element
  ON element.key = introduction.cultural_element_key
JOIN attractions AS attraction
  ON attraction.key = introduction.attraction_key
WHERE introduction.key = $1
`

type GetAttractionCulturalIntroductionRow struct {
	Key                 string             `json:"key"`
	Name                string             `json:"name"`
	Introduction        []byte             `json:"introduction"`
	CulturalElementKey  string             `json:"cultural_element_key"`
	CulturalElementName string             `json:"cultural_element_name"`
	AttractionKey       string             `json:"attraction_key"`
	AttractionName      string             `json:"attraction_name"`
	Latitude            float64            `json:"latitude"`
	Longitude           float64            `json:"longitude"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetAttractionCulturalIntroduction(ctx context.Context, introductionKey string) (GetAttractionCulturalIntroductionRow, error) {
	row := q.db.QueryRow(ctx, getAttractionCulturalIntroduction, introductionKey)
	var i GetAttractionCulturalIntroductionRow
	err := row.Scan(
		&i.Key,
		&i.Name,
		&i.Introduction,
		&i.CulturalElementKey,
		&i.CulturalElementName,
		&i.AttractionKey,
		&i.AttractionName,
		&i.Latitude,
		&i.Longitude,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCulturalContentStats = `-- name: GetCulturalContentStats :one
SELECT
    (SELECT count(*) FROM cultural_elements) AS cultural_element_count,
    (SELECT count(*) FROM attraction_cultural_introductions) AS introduction_count
`

type GetCulturalContentStatsRow struct {
	CulturalElementCount int64 `json:"cultural_element_count"`
	IntroductionCount    int64 `json:"introduction_count"`
}

func (q *Queries) GetCulturalContentStats(ctx context.Context) (GetCulturalContentStatsRow, error) {
	row := q.db.QueryRow(ctx, getCulturalContentStats)
	var i GetCulturalContentStatsRow
	err := row.Scan(&i.CulturalElementCount, &i.IntroductionCount)
	return i, err
}

const getCulturalElement = `-- name: GetCulturalElement :one
SELECT key, name, introduction, created_at, updated_at
FROM cultural_elements
WHERE key = $1
`

func (q *Queries) GetCulturalElement(ctx context.Context, elementKey string) (CulturalElement, error) {
	row := q.db.QueryRow(ctx, getCulturalElement, elementKey)
	var i CulturalElement
	err := row.Scan(
		&i.Key,
		&i.Name,
		&i.Introduction,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertCulturalElementRelation = `-- name: InsertCulturalElementRelation :exec
INSERT INTO cultural_element_relations (
    element_key,
    related_element_key
) VALUES (
    $1,
    $2
)
`

type InsertCulturalElementRelationParams struct {
	ElementKey        string `json:"element_key"`
	RelatedElementKey string `json:"related_element_key"`
}

func (q *Queries) InsertCulturalElementRelation(ctx context.Context, arg InsertCulturalElementRelationParams) error {
	_, err := q.db.Exec(ctx, insertCulturalElementRelation, arg.ElementKey, arg.RelatedElementKey)
	return err
}

const listAllAttractionCulturalIntroductions = `-- name: ListAllAttractionCulturalIntroductions :many
SELECT
    introduction.key,
    introduction.name,
    introduction.introduction,
    introduction.cultural_element_key,
    element.name AS cultural_element_name,
    introduction.attraction_key,
    attraction.name AS attraction_name,
    introduction.latitude,
    introduction.longitude,
    introduction.created_at,
    introduction.updated_at
FROM attraction_cultural_introductions AS introduction
JOIN cultural_elements AS element
  ON element.key = introduction.cultural_element_key
JOIN attractions AS attraction
  ON attraction.key = introduction.attraction_key
ORDER BY introduction.name, introduction.key
`

type ListAllAttractionCulturalIntroductionsRow struct {
	Key                 string             `json:"key"`
	Name                string             `json:"name"`
	Introduction        []byte             `json:"introduction"`
	CulturalElementKey  string             `json:"cultural_element_key"`
	CulturalElementName string             `json:"cultural_element_name"`
	AttractionKey       string             `json:"attraction_key"`
	AttractionName      string             `json:"attraction_name"`
	Latitude            float64            `json:"latitude"`
	Longitude           float64            `json:"longitude"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListAllAttractionCulturalIntroductions(ctx context.Context) ([]ListAllAttractionCulturalIntroductionsRow, error) {
	rows, err := q.db.Query(ctx, listAllAttractionCulturalIntroductions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllAttractionCulturalIntroductionsRow{}
	for rows.Next() {
		var i ListAllAttractionCulturalIntroductionsRow
		if err := rows.Scan(
			&i.Key,
			&i.Name,
			&i.Introduction,
			&i.CulturalElementKey,
			&i.CulturalElementName,
			&i.AttractionKey,
			&i.AttractionName,
			&i.Latitude,
			&i.Longitude,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttractionCulturalIntroductions = `-- name: ListAttractionCulturalIntroductions :many
SELECT
    introduction.key,
    introduction.name,
    introduction.introduction,
    introduction.cultural_element_key,
    element.name AS cultural_element_name,
    introduction.attraction_key,
    attraction.name AS attraction_name,
    introduction.latitude,
    introduction.longitude,
    introduction.created_at,
    introduction.updated_at
FROM attraction_cultural_introductions AS introduction
JOIN cultural_elements AS element
  ON element.key = introduction.cultural_element_key
JOIN attractions AS attraction
  ON attraction.key = introduction.attraction_key
WHERE introduction.attraction_key = $1
ORDER BY introduction.name, introduction.key
`

type ListAttractionCulturalIntroductionsRow struct {
	Key                 string             `json:"key"`
	Name                string             `json:"name"`
	Introduction        []byte             `json:"introduction"`
	CulturalElementKey  string             `json:"cultural_element_key"`
	CulturalElementName string             `json:"cultural_element_name"`
	AttractionKey       string             `json:"attraction_key"`
	AttractionName      string             `json:"attraction_name"`
	Latitude            float64            `json:"latitude"`
	Longitude           float64            `json:"longitude"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListAttractionCulturalIntroductions(ctx context.Context, attractionKey string) ([]ListAttractionCulturalIntroductionsRow, error) {
	rows, err := q.db.Query(ctx, listAttractionCulturalIntroductions, attractionKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAttractionCulturalIntroductionsRow{}
	for rows.Next() {
		var i ListAttractionCulturalIntroductionsRow
		if err := rows.Scan(
			&i.Key,
			&i.Name,
			&i.Introduction,
			&i.CulturalElementKey,
			&i.CulturalElementName,
			&i.AttractionKey,
			&i.AttractionName,
			&i.Latitude,
			&i.Longitude,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttractions = `-- name: ListAttractions :many
SELECT key, name, created_at, updated_at
FROM attractions
ORDER BY name, key
`

func (q *Queries) ListAttractions(ctx context.Context) ([]Attraction, error) {
	rows, err := q.db.Query(ctx, listAttractions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Attraction{}
	for rows.Next() {
		var i Attraction
		if err := rows.Scan(
			&i.Key,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCulturalElementRelations = `-- name: ListCulturalElementRelations :many
SELECT
    LEAST(element_key, related_element_key)::text AS element_key,
    GREATEST(element_key, related_element_key)::text AS related_element_key
FROM cultural_element_relations
ORDER BY element_key, related_element_key
`

type ListCulturalElementRelationsRow struct {
	ElementKey        string `json:"element_key"`
	RelatedElementKey string `json:"related_element_key"`
}

func (q *Queries) ListCulturalElementRelations(ctx context.Context) ([]ListCulturalElementRelationsRow, error) {
	rows, err := q.db.Query(ctx, listCulturalElementRelations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCulturalElementRelationsRow{}
	for rows.Next() {
		var i ListCulturalElementRelationsRow
		if err := rows.Scan(&i.ElementKey, &i.RelatedElementKey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCulturalElements = `-- name: ListCulturalElements :many
SELECT key, name, introduction, created_at, updated_at
FROM cultural_elements
ORDER BY name, key
`

func (q *Queries) ListCulturalElements(ctx context.Context) ([]CulturalElement, error) {
	rows, err := q.db.Query(ctx, listCulturalElements)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CulturalElement{}
	for rows.Next() {
		var i CulturalElement
		if err := rows.Scan(
			&i.Key,
			&i.Name,
			&i.Introduction,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNearbyAttractionCulturalIntroductions = `-- name: ListNearbyAttractionCulturalIntroductions :many
WITH request AS (
    SELECT
        $2::double precision AS latitude,
        $3::double precision AS longitude,
        $4::double precision AS radius_meters
),
distances AS (
    SELECT
        introduction.key,
        introduction.name,
        introduction.introduction,
        introduction.cultural_element_key,
        element.name AS cultural_element_name,
        introduction.attraction_key,
        attraction.name AS attraction_name,
        introduction.latitude,
        introduction.longitude,
        CAST(6371008.8 * 2 * asin(
            LEAST(
                1.0,
                sqrt(
                    power(
                        sin(radians(introduction.latitude - request.latitude) / 2),
                        2
                    ) +
                    cos(radians(request.latitude)) *
                    cos(radians(introduction.latitude)) *
                    power(
                        sin(radians(introduction.longitude - request.longitude) / 2),
                        2
                    )
                )
            )
        ) AS double precision) AS distance_meters
    FROM attraction_cultural_introductions AS introduction
    JOIN cultural_elements AS element
      ON element.key = introduction.cultural_element_key
    JOIN attractions AS attraction
      ON attraction.key = introduction.attraction_key
    CROSS JOIN request
)
SELECT
    distances.key,
    distances.name,
    distances.introduction,
    distances.cultural_element_key,
    distances.cultural_element_name,
    distances.attraction_key,
    distances.attraction_name,
    distances.latitude,
    distances.longitude,
    distances.distance_meters,
    count(*) OVER () AS total_matches
FROM distances
CROSS JOIN request
WHERE distances.distance_meters <= request.radius_meters
ORDER BY distances.distance_meters, distances.name, distances.key
LIMIT $1
`

type ListNearbyAttractionCulturalIntroductionsParams struct {
	ResultLimit  int32   `json:"result_limit"`
	Latitude     float64 `json:"latitude"`
	Longitude    float64 `json:"longitude"`
	RadiusMeters float64 `json:"radius_meters"`
}

type ListNearbyAttractionCulturalIntroductionsRow struct {
	Key                 string  `json:"key"`
	Name                string  `json:"name"`
	Introduction        []byte  `json:"introduction"`
	CulturalElementKey  string  `json:"cultural_element_key"`
	CulturalElementName string  `json:"cultural_element_name"`
	AttractionKey       string  `json:"attraction_key"`
	AttractionName      string  `json:"attraction_name"`
	Latitude            float64 `json:"latitude"`
	Longitude           float64 `json:"longitude"`
	DistanceMeters      float64 `json:"distance_meters"`
	TotalMatches        int64   `json:"total_matches"`
}

func (q *Queries) ListNearbyAttractionCulturalIntroductions(ctx context.Context, arg ListNearbyAttractionCulturalIntroductionsParams) ([]ListNearbyAttractionCulturalIntroductionsRow, error) {
	rows, err := q.db.Query(ctx, listNearbyAttractionCulturalIntroductions,
		arg.ResultLimit,
		arg.Latitude,
		arg.Longitude,
		arg.RadiusMeters,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNearbyAttractionCulturalIntroductionsRow{}
	for rows.Next() {
		var i ListNearbyAttractionCulturalIntroductionsRow
		if err := rows.Scan(
			&i.Key,
			&i.Name,
			&i.Introduction,
			&i.CulturalElementKey,
			&i.CulturalElementName,
			&i.AttractionKey,
			&i.AttractionName,
			&i.Latitude,
			&i.Longitude,
			&i.DistanceMeters,
			&i.TotalMatches,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRelatedCulturalElements = `-- name: ListRelatedCulturalElements :many
SELECT
    related.key,
    related.name,
    related.introduction,
    related.created_at,
    related.updated_at
FROM cultural_element_relations AS relation
JOIN cultural_elements AS related
  ON related.key = CASE
      WHEN relation.element_key = $1
      THEN relation.related_element_key
      ELSE relation.element_key
  END
WHERE relation.element_key = $1
   OR relation.related_element_key = $1
ORDER BY related.name, related.key
LIMIT $2
`

type ListRelatedCulturalElementsParams struct {
	ElementKey   string `json:"element_key"`
	RelatedLimit int32  `json:"related_limit"`
}

func (q *Queries) ListRelatedCulturalElements(ctx context.Context, arg ListRelatedCulturalElementsParams) ([]CulturalElement, error) {
	rows, err := q.db.Query(ctx, listRelatedCulturalElements, arg.ElementKey, arg.RelatedLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CulturalElement{}
	for rows.Next() {
		var i CulturalElement
		if err := rows.Scan(
			&i.Key,
			&i.Name,
			&i.Introduction,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAttraction = `-- name: UpsertAttraction :one
INSERT INTO attractions (
    key,
    name
) VALUES (
    $1,
    $2
)
ON CONFLICT (key) DO UPDATE SET
    name = EXCLUDED.name,
    updated_at = now()
RETURNING key, name, created_at, updated_at
`

type UpsertAttractionParams struct {
	AttractionKey string `json:"attraction_key"`
	Name          string `json:"name"`
}

func (q *Queries) UpsertAttraction(ctx context.Context, arg UpsertAttractionParams) (Attraction, error) {
	row := q.db.QueryRow(ctx, upsertAttraction, arg.AttractionKey, arg.Name)
	var i Attraction
	err := row.Scan(
		&i.Key,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertAttractionCulturalIntroduction = `-- name: UpsertAttractionCulturalIntroduction :one
INSERT INTO attraction_cultural_introductions (
    key,
    name,
    introduction,
    cultural_element_key,
    attraction_key,
    latitude,
    longitude
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
ON CONFLICT (key) DO UPDATE SET
    name = EXCLUDED.name,
    introduction = EXCLUDED.introduction,
    cultural_element_key = EXCLUDED.cultural_element_key,
    attraction_key = EXCLUDED.attraction_key,
    latitude = EXCLUDED.latitude,
    longitude = EXCLUDED.longitude,
    updated_at = now()
RETURNING
    key,
    name,
    introduction,
    cultural_element_key,
    attraction_key,
    latitude,
    longitude,
    created_at,
    updated_at
`

type UpsertAttractionCulturalIntroductionParams struct {
	IntroductionKey    string  `json:"introduction_key"`
	Name               string  `json:"name"`
	Introduction       []byte  `json:"introduction"`
	CulturalElementKey string  `json:"cultural_element_key"`
	AttractionKey      string  `json:"attraction_key"`
	Latitude           float64 `json:"latitude"`
	Longitude          float64 `json:"longitude"`
}

func (q *Queries) UpsertAttractionCulturalIntroduction(ctx context.Context, arg UpsertAttractionCulturalIntroductionParams) (AttractionCulturalIntroduction, error) {
	row := q.db.QueryRow(ctx, upsertAttractionCulturalIntroduction,
		arg.IntroductionKey,
		arg.Name,
		arg.Introduction,
		arg.CulturalElementKey,
		arg.AttractionKey,
		arg.Latitude,
		arg.Longitude,
	)
	var i AttractionCulturalIntroduction
	err := row.Scan(
		&i.Key,
		&i.Name,
		&i.Introduction,
		&i.CulturalElementKey,
		&i.AttractionKey,
		&i.Latitude,
		&i.Longitude,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertCulturalElement = `-- name: UpsertCulturalElement :one
INSERT INTO cultural_elements (
    key,
    name,
    introduction
) VALUES (
    $1,
    $2,
    $3
)
ON CONFLICT (key) DO UPDATE SET
    name = EXCLUDED.name,
    introduction = EXCLUDED.introduction,
    updated_at = now()
RETURNING key, name, introduction, created_at, updated_at
`

type UpsertCulturalElementParams struct {
	ElementKey   string `json:"element_key"`
	Name         string `json:"name"`
	Introduction []byte `json:"introduction"`
}

func (q *Queries) UpsertCulturalElement(ctx context.Context, arg UpsertCulturalElementParams) (CulturalElement, error) {
	row := q.db.QueryRow(ctx, upsertCulturalElement, arg.ElementKey, arg.Name, arg.Introduction)
	var i CulturalElement
	err := row.Scan(
		&i.Key,
		&i.Name,
		&i.Introduction,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertCulturalElementRelation = `-- name: UpsertCulturalElementRelation :exec
INSERT INTO cultural_element_relations (
    element_key,
    related_element_key
) VALUES (
    $1,
    $2
)
ON CONFLICT DO NOTHING
`

type UpsertCulturalElementRelationParams struct {
	ElementKey        string `json:"element_key"`
	RelatedElementKey string `json:"related_element_key"`
}

func (q *Queries) UpsertCulturalElementRelation(ctx context.Context, arg UpsertCulturalElementRelationParams) error {
	_, err := q.db.Exec(ctx, upsertCulturalElementRelation, arg.ElementKey, arg.RelatedElementKey)
	return err
}
