// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Attraction struct {
	Key       string             `json:"key"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type AttractionCulturalIntroduction struct {
	Key                string             `json:"key"`
	Name               string             `json:"name"`
	Introduction       []byte             `json:"introduction"`
	CulturalElementKey string             `json:"cultural_element_key"`
	AttractionKey      string             `json:"attraction_key"`
	Latitude           float64            `json:"latitude"`
	Longitude          float64            `json:"longitude"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type CulturalElement struct {
	Key          string             `json:"key"`
	Name         string             `json:"name"`
	Introduction []byte             `json:"introduction"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type CulturalElementRelation struct {
	ElementKey        string             `json:"element_key"`
	RelatedElementKey string             `json:"related_element_key"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type RecognitionRequestLog struct {
	ID                 int64              `json:"id"`
	RequestID          string             `json:"request_id"`
	ReceivedAt         pgtype.Timestamptz `json:"received_at"`
	CompletedAt        pgtype.Timestamptz `json:"completed_at"`
	DurationMs         int64              `json:"duration_ms"`
	HttpStatus         int16              `json:"http_status"`
	ErrorCode          pgtype.Text        `json:"error_code"`
	RequestBodyBytes   int64              `json:"request_body_bytes"`
	RequestPayload     []byte             `json:"request_payload"`
	ContextImage       []byte             `json:"context_image"`
	ContextMimeType    pgtype.Text        `json:"context_mime_type"`
	ContextImageBytes  int64              `json:"context_image_bytes"`
	FocusImage         []byte             `json:"focus_image"`
	FocusMimeType      pgtype.Text        `json:"focus_mime_type"`
	FocusImageBytes    int64              `json:"focus_image_bytes"`
	ResponsePayload    []byte             `json:"response_payload"`
	ModelIdentifier    pgtype.Text        `json:"model_identifier"`
	PromptVersion      pgtype.Text        `json:"prompt_version"`
	SchemaVersion      pgtype.Text        `json:"schema_version"`
	ResolutionStatus   pgtype.Text        `json:"resolution_status"`
	CulturalElementKey pgtype.Text        `json:"cultural_element_key"`
	CanonicalName      pgtype.Text        `json:"canonical_name"`
}
