// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"context"
)

type Querier interface {
	DeleteCulturalElementRelation(ctx context.Context, arg DeleteCulturalElementRelationParams) error
	GetAttraction(ctx context.Context, attractionKey string) (Attraction, error)
	GetAttractionCulturalIntroduction(ctx context.Context, introductionKey string) (GetAttractionCulturalIntroductionRow, error)
	GetCulturalContentStats(ctx context.Context) (GetCulturalContentStatsRow, error)
	GetCulturalElement(ctx context.Context, elementKey string) (CulturalElement, error)
	InsertCulturalElementRelation(ctx context.Context, arg InsertCulturalElementRelationParams) error
	ListAllAttractionCulturalIntroductions(ctx context.Context) ([]ListAllAttractionCulturalIntroductionsRow, error)
	ListAttractionCulturalIntroductions(ctx context.Context, attractionKey string) ([]ListAttractionCulturalIntroductionsRow, error)
	ListAttractions(ctx context.Context) ([]Attraction, error)
	ListCulturalElementRelations(ctx context.Context) ([]ListCulturalElementRelationsRow, error)
	ListCulturalElements(ctx context.Context) ([]CulturalElement, error)
	ListNearbyAttractionCulturalIntroductions(ctx context.Context, arg ListNearbyAttractionCulturalIntroductionsParams) ([]ListNearbyAttractionCulturalIntroductionsRow, error)
	ListRelatedCulturalElements(ctx context.Context, arg ListRelatedCulturalElementsParams) ([]CulturalElement, error)
	UpsertAttraction(ctx context.Context, arg UpsertAttractionParams) (Attraction, error)
	UpsertAttractionCulturalIntroduction(ctx context.Context, arg UpsertAttractionCulturalIntroductionParams) (AttractionCulturalIntroduction, error)
	UpsertCulturalElement(ctx context.Context, arg UpsertCulturalElementParams) (CulturalElement, error)
	UpsertCulturalElementRelation(ctx context.Context, arg UpsertCulturalElementRelationParams) error
}

var _ Querier = (*Queries)(nil)
